baseURL = '/'
languageCode = 'en-us'
defaultContentLanguage = "en-us"
title = 'Nick Dong'

theme = 'tranquilpeak'

[permalinks]
  posts = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[markup]
  # Set startLevel = 1 to support # title (<h1>title</h1>) otherwise table of content is blank/empty
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[author]
  name = "Nick Dong"
  bio = "Hello, and welcome to Nick Dong's webpage. It includes a gallery of my artworks and also several Minecraft models for EDGE"
  job = "EDGE Public Relations Assistant"
  location = "Richmond B.C. Canada"

  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  gravatarEmail = ""
  # Your profile picture, overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "images/Profile.png"



[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-home\" aria-hidden=\"true\"></i>"
  url = "/"
[[menu.main]]
  weight = 2
  identifier = "categories"
  name = "Categories"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-bookmark\" aria-hidden=\"true\"></i>"
  url = "/categories"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-tags\" aria-hidden=\"true\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 4
  identifier = "archives"
  name = "Archives"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-archive\" aria-hidden=\"true\"></i>"
  url = "/archives"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fas fa-lg fa-question\" aria-hidden=\"true\"></i>"
  url = "/#about"


#Ask if has github, stackoverflow, twitter
[[menu.links]]
  weight = 1
  identifier = "instagram"
  name = "Instagram"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-instagram\" aria-hidden=\"true\"></i>"
  url = "https://www.instagram.com/n.n4111/"
[[menu.links]]
  weight = 2
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\" aria-hidden=\"true\"></i>"
  url = "https://github.com/Nicool333"






# -------------
# Customization
# -------------
[params]
  # -----------
  # Description
  # -----------
  description = "A personal website for Nick Dong"

  # ------------------
  # Syntax highlighter
  # ------------------
  # Syntax highlighter, possible choice between: "highlight.js" and "prism.js"
  # You can comment it to disable syntax highlighting
  syntaxHighlighter = "prism.js"

  # -----------
  # Date format
  # -----------
  # Customize date format use to render blog post date, categories and other
  # You must use date format used by Go Time package https://golang.org/pkg/time/
  # Months (not work with short month like "jan", "feb", etc) are translated if translation exists on i18n folders
  # Default format is: January 2, 2006
  #  dateFormat = "2 January 2006"

  # ---------------------------
  # Posts related configuration
  # ---------------------------
  # Global keywords configuration. Following keywords will be add to every pages
  #  keywords = ["design, arts"]

  # Hide sidebar on all article page to let article take full width to improve reading, and enjoy wide images and cover images. (true: enable, false: disable)
  clearReading = true

  # Define categories will create hierarchy between parents: `categories = ["foo", "bar"]` will consider "bar" a sub-category of "foo".
  # If false it will flat categories.
  hierarchicalCategories = true

  # Display `Next` on left side of the pagination, and `Prev` on right side one.
  # If you set this value to `true`, these positions swap.
  #  swapPaginator = true

  # ---------------------
  # Sidebar configuration
  # ---------------------
  # Customization
  # Define the behavior of the sidebar
  # 1: Display extra large sidebar on extra large screen, large sidebar on large screen,
  #    medium sidebar on medium screen and header bar on small screen and
  # extra large sidebar is swiped on extra large screen and large sidebar on all lower screen (default)
  # 2: Display large sidebar on large screen, medium sidebar on medium screen and
  #    header bar on small screen and large sidebar is swiped
  # 3: Display medium sidebar on large and medium screen and header bar on small screen and
  #    medium sidebar is swiped
  # 4: Display header bar on all screens, extra large sidebar is swiped on extra large screen and
  #    large sidebar is swiped on all lower screens
  # 5: Display header bar on all screens and large sidebar is swiped on large screen
  # 6: Display header bar on all screens and medium sidebar is swiped
  sidebarBehavior = 1

  # Customize link of author avatar in sidebar
  #  [params.sidebar.profile]
  #    url = "/#about"

  # -------------------
  # Media configuration
  # -------------------

  
  #TODO: If want to change cover picture, modify cover image
  # Your blog cover picture. I STRONGLY recommend you to use a CDN to speed up loading of pages.
  # There is many free CDN like Cloudinary or you can also use indirectly
  # by using services like Google Photos.
  # Current image is on AWS S3 and delivered by AWS CloudFront.
  # Otherwise put your image, for example `cover.jpg` in folder `static/images/`,
  # and use relative url : `images/cover.jpg`
  coverImage = "images/cover.jpg"

  # Display an image gallery at the end of a post which have photos variables (false: disabled, true: enabled)
  imageGallery = true

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true
  # Display thumbnail image at the right of title in index pages (`right`, `left` or `bottom`)
  # Set this value to `right` if you have old posts to keep the old style on them
  # and define `thumbnailImagePosition` on a post to overwrite this setting
  thumbnailImagePosition = "bottom"
  # Automatically select the cover image or the first photo from the gallery of a post if there is no thumbnail image as the thumbnail image
  # Set this value to `true` if you have old posts that use the cover image or the first photo as the thumbnail image
  # and set `autoThumbnailImage` to `false` on a post to overwrite this setting
  autoThumbnailImage = true

  # Your favicon path, default is "/favicon.png"
  #  favicon = "/favicon.png"


  # --------------------
  # Header configuration
  # --------------------
  # The link at the right of the header is customizable
  # You can add a link (as an icon) at the right of the header instead of the author's gravatar image or author's picture.
  # By default, author's gravatar or author's picture is displayed.
  #  url: /#search
  #  icon: search
  #  class: st-search-show-outputs
  [params.header.rightLink]
    class = ""
    icon = ""
    url = "/#about"

  # --------------------
  # Footer configuration
  # --------------------
  # Customize copyright value "© 2017 <CUSTOMIZATION>. All Rights Reserved"
  #  [params.footer]
  #    copyright = "<a href=\"https://github.com/kakawait\">kakawait</a>"
